# Generated by Django 3.2.2 on 2021-05-12 10:48

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game_genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie_genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('age_limit', models.CharField(max_length=100)),
                ('producer', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('number_of_movies', models.IntegerField()),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.movie_genre')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('series_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Online_game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('number_of_gamers', models.TextField()),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.game_genre')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('online_game_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Offline_game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.game_genre')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('offline_game_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('age_limit', models.CharField(max_length=100)),
                ('producer', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration', models.FloatField()),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.movie_genre')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('films_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
